import serial
import serial.tools.list_ports
import time
import csv
import sys

# Configuration
BAUD_RATE = 115200
DURATION_MINUTES = 2 # 120 seconds test as required
DURATION_SECONDS = DURATION_MINUTES * 60
OUTPUT_FILE = "power_efficiency_data.csv"

def get_com_port():
    ports = serial.tools.list_ports.comports()
    if not ports:
        print("No COM ports found. Please ensure your ESP32 is plugged in.")
        sys.exit(1)
    
    print("Available COM Ports:")
    for i, port in enumerate(ports):
        print(f"[{i}] {port.device} - {port.description}")
        
    if len(ports) == 1:
        print(f"Auto-selecting {ports[0].device}")
        return ports[0].device

    try:
        selection = int(input("Select the COM port index for your ESP32: "))
        return ports[selection].device
    except (ValueError, IndexError):
        print("Invalid selection.")
        sys.exit(1)

def main():
    print("=====================================================")
    print(f"  ESP32 Power Efficiency Logger ({DURATION_SECONDS} Seconds) ")
    print("=====================================================")
    com_port = get_com_port()
    
    print(f"\nConnecting to {com_port} at {BAUD_RATE} baud...")
    
    try:
        ser = serial.Serial(com_port, BAUD_RATE, timeout=1)
    except Exception as e:
        print(f"\n[!] Failed to connect to {com_port}: {e}")
        print("[!] IMPORTANT: Make sure the Serial Monitor in Arduino IDE is CLOSED before running this script!")
        sys.exit(1)
        
    print(f"Successfully connected. Logging data for exactly {DURATION_SECONDS} seconds...")
    print(f"Data will be saved to '{OUTPUT_FILE}' in the current directory.")
    
    start_time = time.time()
    
    with open(OUTPUT_FILE, mode='w', newline='', encoding='utf-8') as f:
        writer = csv.writer(f)
        # Expected Header Format: Timestamp + 5 ESP32 Telemetry Columns
        writer.writerow(["Timestamp(s)", "Lux", "LED_Brightness", "InstantPower_W", "SavedPower_W", "AccumulatedSavings_Wh"])
        
        last_print_time = 0
        try:
            while True:
                elapsed_time = time.time() - start_time
                if elapsed_time > DURATION_SECONDS:
                    print(f"\n\nTime's up! {DURATION_SECONDS} seconds of logging completed.")
                    break
                    
                if ser.in_waiting > 0:
                    try:
                        line = ser.readline().decode('utf-8').strip()
                        if line:
                            # Skip standard boot prints and headers from ESP32
                            if any(x in line for x in ["Lux", "System:", "Error:", "ets ", "rst:"]):
                                print(f"\n[ESP32]: {line}")
                                continue
                            
                            # Parse the CSV line from ESP32
                            parts = line.split(',')
                            # We expect 5 values generated by your ESP32 script
                            if len(parts) == 5:
                                # Inject the precise PC-side timestamp
                                row = [f"{elapsed_time:.2f}"] + parts
                                writer.writerow(row)
                                # Force write to disk immediately
                                f.flush()
                                
                                # Print progress
                                print(f"[{elapsed_time:05.1f}s / {DURATION_SECONDS}s] Logged: {line}" + " "*10, end='\r')
                                last_print_time = elapsed_time
                            else:
                                # Ignore malformed packets if they occur
                                pass 
                    except UnicodeDecodeError:
                        pass # Ignore corrupted serial bytes 
                else:
                    # Update timer smoothly even when no data is arriving
                    if elapsed_time - last_print_time > 0.1:
                        print(f"[{elapsed_time:05.1f}s / {DURATION_SECONDS}s] Waiting for data..." + " "*15, end='\r')
                        last_print_time = elapsed_time
                        
                time.sleep(0.01) # Small sleep to prevent 100% CPU usage
                        
        except KeyboardInterrupt:
            print("\n\nLogging stopped manually by user (Ctrl+C).")
            
    ser.close()
    print(f"Done. Port closed. Data safely secured in '{OUTPUT_FILE}'.")

if __name__ == "__main__":
    main()
